name: Deploy to GitHub Pages

# Le damos permiso explícito para publicar Pages
permissions:
  contents: read   # lee tu repo
  pages: write     # escribe en GitHub Pages

on:
  push:
    branches:
      - principal  # tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout completo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Ahora usamos tu PAT en vez de GITHUB_TOKEN
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
